### ISSUE TITLE
Alacritty window disappears in Gnome overview

### ISSUE THREAD

**Issue by MonsieurLanza** [axxapy/gnome-alacritty-toggle#1]
Love this extension. 

Anyway this makes Alacritty window disappear in Gnome Overview, which I find annoying. Not sure if this is intended ? 

Edit: Checked the code, this is indeed intended. Could you add it to the extension description ? I searched the reason of the behaviour for a while.

(As for myself, I’ll just fork, thanks. ^^)

**Comment by axxapy** [comment]
I have sent new version to review. Update will be available on the extensions portal shortly.

It adds setting to disable this behavior: https://github.com/axxapy/gnome-alacritty-toggle#settings

**Comment by MonsieurLanza** [comment]
Much thanks.
