### ISSUE TITLE
gnome 42 support

### ISSUE THREAD

**Issue by GiulianoPalazzi** [axxapy/gnome-alacritty-toggle#2]
Hi,
could you please add gnome 42 support on the gnome extensions website.
Thanks!

**Comment by joscherrer** [comment]
@axxapy I've created a PR that fixes this issue

@GiulianoPalazzi in the meantime, you can install manually my fork : 
```bash
git clone https://github.com/joscherrer/gnome-alacritty-toggle ~/.local/share/gnome-shell/extensions/toggle-alacritty@itstime.tech
```

**Comment by axxapy** [comment]
gnome 43 also in master
